org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
# Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
neo_version=26.1.2.114
neo_version_range=[26.1.2.71,)
xaeros_minimap_file_id=8849900
## Mod Properties
mod_id=ametrin_structures
mod_name=Ametrin Structures
mod_license=MIT
mod_version=0.2.0-beta
mod_group_id=com.ametrin
